/**
 * github.ts
 * GitHub App installation / connection endpoints.
 *
 * The frontend NEVER creates a GitHub App or handles installation tokens.
 * It only reads the connection state the backend confirms, and redirects the
 * user to the single PR Sentinel GitHub App install URL.
 */

import { apiRequest } from "./client";
import type { GitHubInstallationStatus, Repository } from "./types";

export const githubApi = {
  /**
   * GET /github/installation
   * Returns whether the authenticated user has a confirmed GitHub App
   * installation. This is the single source of truth for "connected".
   */
  getInstallation(signal?: AbortSignal): Promise<GitHubInstallationStatus> {
    return apiRequest<GitHubInstallationStatus>("/github/installation", { signal });
  },

  /**
   * GET /github/repositories
   * Repositories the installation has access to.
   */
  getRepositories(signal?: AbortSignal): Promise<Repository[]> {
    return apiRequest<Repository[]>("/github/repositories", { signal });
  },

  /**
   * GET /github/install/complete?installation_id=...&state=...
   * Ask the backend to verify a freshly-completed installation and link it to
   * the authenticated user. GitHub redirects back with an `installation_id`
   * (and optionally `state` / `setup_action`) which we forward so the backend
   * can validate and sync the installation.
   *
   * The backend handles two cases:
   *   • With state   → validates the Redis token generated by startInstall()
   *   • Without state → safe because the JWT cookie proves identity
   */
  completeInstall(
    input: {
      installationId?: string | null;
      state?: string | null;
      setupAction?: string | null;
    },
    signal?: AbortSignal
  ): Promise<GitHubInstallationStatus> {
    const params = new URLSearchParams();
    if (input.installationId) params.set("installation_id", input.installationId);
    if (input.state)          params.set("state", input.state);
    if (input.setupAction)    params.set("setup_action", input.setupAction);
    return apiRequest<GitHubInstallationStatus>(
      `/github/install/complete?${params.toString()}`,
      { signal }
    );
  },

  /**
   * POST /github/install/start
   * Generate a state-signed GitHub App install URL on the backend and return
   * it. The frontend then redirects the user to this URL. This ties the
   * install flow to the logged-in user via a Redis state token.
   */
  startInstall(signal?: AbortSignal): Promise<{ installUrl: string }> {
    return apiRequest<{ installUrl: string }>("/github/install/start", {
      method: "POST",
      signal,
    });
  },
};

/**
 * Public install URL for the one PR Sentinel GitHub App. Configured via a
 * public env var — it contains no secrets. If the backend prefers to build
 * the URL (e.g. to attach a signed `state`), it can expose it instead.
 */
export function getInstallUrl(): string | null {
  return process.env.NEXT_PUBLIC_GITHUB_APP_INSTALL_URL || null;
}
