"use client";

import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, GitPullRequest, RefreshCw, ShieldAlert, Sparkles } from "lucide-react";

export default function PullRequestReviewPage() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  return <main className="review-page"><header className="review-topbar"><button className="back-button" onClick={() => router.push("/dashboard/pull-requests")}><ArrowLeft size={16} />Back to pull requests</button><div className="review-actions"><button className="review-ghost" disabled><RefreshCw size={15} />Retry review</button></div></header><div className="review-layout"><section className="review-main"><div className="review-breadcrumb"><span>Pull requests</span><span>/</span><strong>#{params.id}</strong></div><div className="review-title"><div><span className="drawer-kicker">PR #{params.id}</span><h1>Review workspace</h1><p>This pull request is not available in the current workspace.</p></div><span className="status-badge warning">Connection required</span></div><section className="review-card ai-card"><div className="review-card-header"><div className="ai-title"><span className="ai-icon"><Sparkles size={15} /></span><div><h2>Review lifecycle</h2><p>Processing status will appear here after GitHub is connected.</p></div></div></div><div className="lifecycle-list"><div className="lifecycle-item"><span className="lifecycle-marker"><ShieldAlert size={14} /></span><div><strong>Waiting for repository access</strong><p>PR Sentinel cannot fetch the diff or repository context yet.</p></div></div><div className="lifecycle-item"><span className="lifecycle-marker"><GitPullRequest size={14} /></span><div><strong>Queued → analyzing → findings ready</strong><p>These states are only shown when a real webhook event is received.</p></div></div></div></section><section className="review-card"><div className="workspace-empty"><ShieldAlert size={26} /><h2>No review data</h2><p>Connect the repository that contains PR #{params.id}, then return here after the webhook has been acknowledged.</p><button className="primary-button" onClick={() => router.push("/dashboard/repositories")}>Set up a repository</button></div></section></section><aside className="review-sidebar"><section className="review-card"><h2>Review facts</h2><div className="review-facts"><div><span>Risk score</span><strong>—</strong></div><div><span>Changed files</span><strong>—</strong></div><div><span>Findings</span><strong>—</strong></div></div></section><section className="review-card"><h2>Required access</h2><p className="ai-copy">Repository contents, pull request metadata, checks, and comment permissions are required for a complete review.</p></section></aside></div></main>;
}
