"use client";

import { useEffect, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { Activity, AlertTriangle, Bell, CheckCircle2, ChevronRight, Code2, GitPullRequest, LayoutDashboard, LogOut, Menu, Moon, Settings2, ShieldCheck, Sparkles, Sun, X } from "lucide-react";
import { getDisplayName, getInitials, getStoredUser, isAuthenticated, logout } from "@/lib/auth";

type PageKind = "pull-requests" | "findings" | "repositories" | "activity" | "settings";

const nav = [
  ["Overview", "/dashboard", LayoutDashboard],
  ["Pull requests", "/dashboard/pull-requests", GitPullRequest],
  ["Findings", "/dashboard/findings", ShieldCheck],
  ["Repositories", "/dashboard/repositories", Code2],
  ["Activity", "/dashboard/activity", Activity],
  ["Settings", "/dashboard/settings", Settings2],
] as const;

function EmptyState({ title, body, action, onAction }: { title: string; body: string; action?: string; onAction?: () => void }) {
  return <div className="workspace-empty"><div className="empty-icon"><Sparkles size={18} /></div><h2>{title}</h2><p>{body}</p>{action && <button className="primary-button" onClick={onAction}>{action}<ChevronRight size={15} /></button>}</div>;
}

function PageHeader({ eyebrow, title, body, action, onAction }: { eyebrow: string; title: string; body: string; action?: string; onAction?: () => void }) {
  return <header className="workspace-page-header"><div><div className="eyebrow"><span className="eyebrow-line" />{eyebrow}</div><h1>{title}</h1><p>{body}</p></div>{action && <button className="primary-button" onClick={onAction}>{action}<ChevronRight size={15} /></button>}</header>;
}

function WorkspaceShell({ children, title }: { children: React.ReactNode; title: string }) {
  const router = useRouter();
  const pathname = usePathname();
  const [mobile, setMobile] = useState(false);
  const [menu, setMenu] = useState(false);
  const user = getStoredUser();
  useEffect(() => { if (!isAuthenticated()) router.replace("/sign-in"); }, [router]);
  const name = user ? getDisplayName(user) : "Workspace member";
  return <div className="app-shell"><aside className={`sidebar ${mobile ? "sidebar-open" : ""}`}><div className="brand-row"><div className="brand-mark"><Sparkles size={16} /></div><span className="brand-name">pr<span>·</span>sentinel</span><button className="icon-button close-mobile" onClick={() => setMobile(false)} aria-label="Close navigation"><X /></button></div><div className="workspace-switcher"><div className="workspace-avatar">W</div><div className="workspace-copy"><strong>Workspace</strong><span>GitHub not connected</span></div></div><nav className="nav-list" aria-label="Workspace navigation"><p className="nav-label">Workspace</p>{nav.map(([label, href, Icon]) => <button key={href} className={`nav-item ${pathname === href || (href !== "/dashboard" && pathname.startsWith(href)) ? "active" : ""}`} onClick={() => { router.push(href); setMobile(false); }}><Icon size={17} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="health-card"><div className="health-title"><span className="pulse-dot" />Connection required</div><span>Connect GitHub to enable monitoring</span></div><div className="user-row"><div className="user-avatar">{user ? getInitials(user) : "U"}</div><div className="user-copy"><strong>{name}</strong><span>{user?.githubId ? "GitHub · OAuth" : "Account"}</span></div><button className="icon-button" onClick={() => setMenu(!menu)} aria-label="Account menu"><Menu size={17} /></button>{menu && <button className="account-popover" onClick={async () => { await logout(); router.replace("/sign-in"); }}><LogOut size={14} />Sign out</button>}</div></div></aside><main className="main-content"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMobile(true)} aria-label="Open navigation"><Menu /></button><div className="breadcrumbs"><span>Workspace</span><span className="crumb-separator">/</span><strong>{title}</strong></div><div className="topbar-actions"><button className="icon-button" aria-label="Notifications"><Bell size={17} /></button><button className="icon-button" aria-label="Toggle theme"><Moon size={17} /></button></div></header>{children}</main></div>;
}

function PullRequestsPage() { return <><PageHeader eyebrow="PULL REQUESTS" title="Review queue" body="Every pull request that enters your configured review workflow." action="Connect GitHub" /><section className="workspace-panel"><div className="panel-header"><div><h2>Pull requests</h2><p>Nothing is connected to this workspace yet.</p></div><span className="status-badge warning">Connection required</span></div><EmptyState title="Your review queue is empty" body="Connect a GitHub repository to receive webhook events and begin processing pull requests." action="Set up a repository" /></section></>; }
function FindingsPage() { return <><PageHeader eyebrow="FINDINGS" title="Security findings" body="Review issues detected across your pull request history." /><section className="workspace-panel"><div className="panel-header"><div><h2>All findings</h2><p>Findings will appear after the first completed review.</p></div></div><EmptyState title="No findings yet" body="PR Sentinel will group actionable findings here by severity, category, repository, and pull request." /></section></>; }
function RepositoriesPage() { const [started, setStarted] = useState(false); return <><PageHeader eyebrow="REPOSITORIES" title="Repository setup" body="Choose which GitHub repositories PR Sentinel is allowed to review." action={started ? undefined : "Connect GitHub"} onAction={() => setStarted(true)} /><section className="setup-grid"><div className="workspace-panel setup-card"><div className="setup-step"><span>1</span><div><h2>Install the GitHub App</h2><p>Grant only the repository and pull request permissions required to receive events and publish review comments.</p></div></div><div className="setup-step"><span>2</span><div><h2>Select repositories</h2><p>Choose specific repositories instead of enabling access to every repository in your account.</p></div></div><div className="setup-step"><span>3</span><div><h2>Verify the webhook</h2><p>Send a test event and confirm that PR Sentinel can acknowledge and process it.</p></div></div>{started && <div className="inline-notice"><AlertTriangle size={16} />GitHub connection is not configured in this environment. No repository access was granted.</div>}</div><div className="workspace-panel"><div className="panel-header"><div><h2>Connected repositories</h2><p>Least-privilege repository access.</p></div></div><EmptyState title="No repositories connected" body="Repository configuration is required before reviews can be received." /></div></section></>; }
function ActivityPage() { return <><PageHeader eyebrow="ACTIVITY" title="Audit activity" body="A chronological record of workspace and review events." /><section className="workspace-panel"><div className="panel-header"><div><h2>Event history</h2><p>Events are retained and displayed here once a workspace is connected.</p></div></div><EmptyState title="No events yet" body="Webhook delivery, review processing, comments, retries, and configuration changes will be recorded here." /></section></>; }
function SettingsPage() { const [saved, setSaved] = useState(false); return <><PageHeader eyebrow="SETTINGS" title="Workspace settings" body="Control review policy, notifications, members, and destructive actions." /><div className="settings-grid"><section className="workspace-panel settings-card"><h2>Review policy</h2><p>These controls will apply to every connected repository.</p><label className="setting-row"><span><strong>Review opened pull requests</strong><small>Start a review when GitHub sends a pull_request event.</small></span><input type="checkbox" disabled /></label><label className="setting-row"><span><strong>Publish comments automatically</strong><small>Requires explicit GitHub write permission.</small></span><input type="checkbox" disabled /></label><label className="setting-row"><span><strong>Block on high-confidence findings</strong><small>Policy enforcement requires a connected repository.</small></span><input type="checkbox" disabled /></label></section><section className="workspace-panel settings-card"><h2>Notifications</h2><p>Delivery preferences for review results and failures.</p><label className="setting-row"><span><strong>Review completion email</strong><small>Send when a review reaches a terminal state.</small></span><input type="checkbox" disabled /></label><label className="setting-row"><span><strong>Webhook failure alerts</strong><small>Notify workspace members when retries are exhausted.</small></span><input type="checkbox" disabled /></label></section><section className="workspace-panel settings-card danger-zone"><h2>Danger zone</h2><p>Destructive workspace actions will become available after setup.</p><button className="secondary-button" disabled onClick={() => setSaved(true)}>{saved ? "Request submitted" : "Delete workspace"}</button></section></div></>; }

export default function WorkspacePage({ kind }: { kind: PageKind }) { const title = kind === "pull-requests" ? "Pull requests" : kind[0].toUpperCase() + kind.slice(1); return <WorkspaceShell title={title}><div className="content-wrap workspace-content">{kind === "pull-requests" ? <PullRequestsPage /> : kind === "findings" ? <FindingsPage /> : kind === "repositories" ? <RepositoriesPage /> : kind === "activity" ? <ActivityPage /> : <SettingsPage />}</div></WorkspaceShell>; }

export { WorkspaceShell, PageHeader, EmptyState };
